feature_matcher:
  detector: superpoint
  flann_index_params:
    algorithm: 1
    trees: 5
  flann_search_params:
    checks: 50
  img_size_scale: 0.33
  match_conf: 0.7
  max_features: 300
  ransac_reproj_threshold: 10.0
  super_point:
    conf_thresh: 0.002
    nms_dist: 8
    nn_thresh: 0.9
    weights_path: models/superpoint_v1.pth
